package main

import (
	"archive/tar"
	"bytes"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

const testManifest = `# This file was generated by Gleam
# You typically do not need to edit this file

packages = [
  { name = "gleam_stdlib", version = "1.0.0", build_tools = ["gleam"], requirements = [], otp_app = "gleam_stdlib", source = "hex", outer_checksum = "960090C2FB391784BB34267B099DC9315CC1B1F6013E7415BC763CEF1905D7D3" },
  { name = "gleeunit", version = "1.10.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "gleeunit", source = "hex", outer_checksum = "254B697FE72EEAD7BF82E941723918E421317813AC49923EE76A18C788C61E72" },
  { name = "hinoto", version = "0.0.1", build_tools = ["gleam"], requirements = ["mist"], source = "git", repo = "https://github.com/Comamoca/hinoto", commit = "7044cbd33f9a0cefa94bacc0514d8db08f8ac194" },
]

[requirements]
gleam_stdlib = { version = ">= 0.44.0 and < 2.0.0" }
`

const testGleamToml = `name = "demo"
version = "1.0.0"
licences = ["MIT", "Apache-2.0"]

# Fill out these fields if you intend to publish to Hex.
# description = ""

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
hinoto = {
  git = "https://github.com/Comamoca/hinoto",
  ref = "main",
}

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
`

func writeFile(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestParseManifest(t *testing.T) {
	path := filepath.Join(t.TempDir(), manifestFile)
	writeFile(t, path, testManifest)

	pkgs, err := parseManifest(path)
	if err != nil {
		t.Fatal(err)
	}
	want := []manifestPkg{
		{pkgRef: pkgRef{name: "gleam_stdlib", source: "hex", checksum: "960090C2FB391784BB34267B099DC9315CC1B1F6013E7415BC763CEF1905D7D3"}, line: 5, col: 11},
		{pkgRef: pkgRef{name: "gleeunit", source: "hex", checksum: "254B697FE72EEAD7BF82E941723918E421317813AC49923EE76A18C788C61E72"}, line: 6, col: 11},
		{pkgRef: pkgRef{name: "hinoto", source: "git"}, line: 7, col: 11},
	}
	if !reflect.DeepEqual(pkgs, want) {
		t.Errorf("parseManifest:\n got %+v\nwant %+v", pkgs, want)
	}
}

func TestParseGleamToml(t *testing.T) {
	path := filepath.Join(t.TempDir(), gleamFile)
	writeFile(t, path, testGleamToml)

	file, err := parseGleamToml(path)
	if err != nil {
		t.Fatal(err)
	}
	if file.licence != "MIT OR Apache-2.0" {
		t.Errorf("licence = %q, want %q", file.licence, "MIT OR Apache-2.0")
	}
	if file.licenceLine != 3 || file.licenceCol != 1 {
		t.Errorf("licence position = %d:%d, want 3:1", file.licenceLine, file.licenceCol)
	}
	want := []depEntry{
		{name: "gleam_stdlib", line: 9, col: 1},
		{name: "hinoto", line: 10, col: 1},
		{name: "gleeunit", line: 16, col: 1},
	}
	if !reflect.DeepEqual(file.deps, want) {
		t.Errorf("deps:\n got %+v\nwant %+v", file.deps, want)
	}
}

func TestParseManifestEmptyArray(t *testing.T) {
	path := filepath.Join(t.TempDir(), manifestFile)
	writeFile(t, path, "packages = []\n\n[requirements]\n")

	pkgs, err := parseManifest(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 0 {
		t.Errorf("parseManifest = %+v, want no packages", pkgs)
	}
}

func TestParseHexMetadata(t *testing.T) {
	body := `{<<"name">>, <<"gleam_stdlib"/utf8>>}.
{<<"licenses">>, [<<"Apache-2.0"/utf8>>]}.
{<<"files">>, [
  <<"LICENCE"/utf8>>
]}.
`
	got := parseHexMetadata(body)
	if want := []string{"Apache-2.0"}; !reflect.DeepEqual(got, want) {
		t.Errorf("parseHexMetadata = %v, want %v", got, want)
	}

	dual := `{<<"licenses">>, [<<"MIT">>, <<"Apache-2.0"/utf8>>]}.`
	if got, want := parseHexMetadata(dual), []string{"MIT", "Apache-2.0"}; !reflect.DeepEqual(got, want) {
		t.Errorf("parseHexMetadata = %v, want %v", got, want)
	}

	if got := parseHexMetadata(`{<<"name">>, <<"x"/utf8>>}.`); got != nil {
		t.Errorf("parseHexMetadata without a licenses field = %v, want nil", got)
	}
}

func TestHexTarballLicences(t *testing.T) {
	var buf bytes.Buffer
	entries := tar.NewWriter(&buf)
	metadata := `{<<"name">>, <<"mist"/utf8>>}.
{<<"licenses">>, [<<"Apache-2.0"/utf8>>]}.
`
	writeTarEntry(t, entries, "metadata.config", metadata)
	writeTarEntry(t, entries, "VERSION", "3")
	if err := entries.Close(); err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(t.TempDir(), "checksum.tar")
	writeFile(t, path, buf.String())

	got, err := hexTarballLicences(path)
	if err != nil {
		t.Fatal(err)
	}
	if want := []string{"Apache-2.0"}; !reflect.DeepEqual(got, want) {
		t.Errorf("hexTarballLicences = %v, want %v", got, want)
	}
}

func writeTarEntry(t *testing.T, entries *tar.Writer, name, body string) {
	t.Helper()
	if err := entries.WriteHeader(&tar.Header{Name: name, Mode: 0o644, Size: int64(len(body))}); err != nil {
		t.Fatal(err)
	}
	if _, err := entries.Write([]byte(body)); err != nil {
		t.Fatal(err)
	}
}

func TestFindRootSkipsBuildPackages(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, gleamFile), "name = \"demo\"\n")
	dependency := filepath.Join(root, buildDir, packagesDir, "gleam_stdlib")
	writeFile(t, filepath.Join(dependency, gleamFile), "name = \"gleam_stdlib\"\n")

	got, err := findRoot(dependency)
	if err != nil {
		t.Fatal(err)
	}
	if got != root {
		t.Errorf("findRoot(%s) = %s, want %s", dependency, got, root)
	}
}

func TestDiagnosticFormat(t *testing.T) {
	d := diagnostic{file: "/proj/manifest.toml", line: 12, col: 3, severity: severityWarning, message: "unknown licence (not downloaded)"}

	if got, want := d.format(defaultFormat), "/proj/manifest.toml:12:3: W: unknown licence (not downloaded)"; got != want {
		t.Errorf("format = %q, want %q", got, want)
	}
	if got, want := d.format("%f:%l:%c: %m"), "/proj/manifest.toml:12:3: unknown licence (not downloaded)"; got != want {
		t.Errorf("format = %q, want %q", got, want)
	}
	if got, want := d.format("100%% %m"), "100% unknown licence (not downloaded)"; got != want {
		t.Errorf("format = %q, want %q", got, want)
	}
}

// TestScanProject walks a project through the whole pipeline: a directory
// argument, licence lookup in the installed package metadata, and a hex
// dependency that was never downloaded.
func TestScanProject(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, gleamFile), testGleamToml)
	writeFile(t, filepath.Join(root, manifestFile), testManifest)
	writeFile(t, filepath.Join(root, buildDir, packagesDir, "gleam_stdlib", gleamFile),
		"name = \"gleam_stdlib\"\nlicences = [\"Apache-2.0\"]\n")
	writeFile(t, filepath.Join(root, buildDir, packagesDir, "hinoto", gleamFile),
		"name = \"hinoto\"\nlicences = [\"MIT\"]\n")

	// Keep the hex cache out of the picture so lookups stay deterministic.
	t.Setenv("GLEAM_CACHE", filepath.Join(root, "empty-cache"))
	t.Setenv("XDG_CACHE_HOME", filepath.Join(root, "empty-cache"))

	got, err := scan(filepath.Join(root, gleamFile), "")
	if err != nil {
		t.Fatal(err)
	}
	want := []string{
		"/proj/gleam.toml:3:1: I: MIT OR Apache-2.0",
		"/proj/gleam.toml:9:1: I: Apache-2.0",
		"/proj/gleam.toml:10:1: I: MIT",
		"/proj/gleam.toml:16:1: W: unknown licence (not downloaded)",
	}
	if got := formatAll(got, filepath.Join(root, gleamFile)); !reflect.DeepEqual(got, want) {
		t.Errorf("scan(gleam.toml):\n got %v\nwant %v", got, want)
	}

	got, err = scan(root, "")
	if err != nil {
		t.Fatal(err)
	}
	want = []string{
		"/proj/manifest.toml:5:11: I: Apache-2.0",
		"/proj/manifest.toml:6:11: W: unknown licence (not downloaded)",
		"/proj/manifest.toml:7:11: I: MIT",
	}
	if got := formatAll(got, filepath.Join(root, manifestFile)); !reflect.DeepEqual(got, want) {
		t.Errorf("scan(dir):\n got %v\nwant %v", got, want)
	}
}

// formatAll renders diagnostics against path, which stands in for the temporary
// project directory of a test.
func formatAll(diags []diagnostic, path string) []string {
	const proj = "/proj/"
	out := make([]string, 0, len(diags))
	for _, d := range diags {
		out = append(out, strings.Replace(d.file, filepath.Dir(path)+"/", proj, 1)+d.format(":%l:%c: %t: %m"))
	}
	return out
}
