[[plugins]]
repo = 'ghifarit53/tokyonight-vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = 0
hook_source = 'call coil398#init#coc#hook_source()'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'mattn/mkdpreview-vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = """
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_auto_insert_bullets = 0
let g:vim_markdown_new_list_item_indent = 0
"""

[[plugins]]
repo = 'kannokanno/previm'
hook_add = """
autocmd BufRead,BufNewFile *.md set filetype=markdown
let g:previm_open_cmd = 'midori'
" ctrl pでプレビュー
nnoremap <silent> <C-p> :PrevimOpen<CR>
"""

# [[plugins]]
# repo = 'tyru/open-browser.vim'
# hook_add = """
# let g:netrw_nogx = 1 " disable netrw's gx mapping.
# nmap gx <Plug>(openbrowser-smart-search)
# vmap gx <Plug>(openbrowser-smart-search)
# """

[[plugins]]
repo = '~/ablaze/ablaze.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
# hook_add = """
# let s:denite_win_width_percent = 0.85
# let s:denite_win_height_percent = 0.7
# " denite
# "  <C-o> open Denite-file-buffer-list
# "    <Esc>      close Denite-file-buffer-list
# "    <Space>    select multiple files/buffers
# "    <CR>       open files/buffers
# "    o          open files/buffers
# "    s          open files/buffers in split windows (horizonal)
# "    v          open files/buffers in split windows (vertical)
# "    i          filter by string
# "    ..         move to directory above
# nnoremap <silent> <C-o> :<C-u>Denite file buffer file:new<CR>
# autocmd FileType denite call s:denite_my_settings()
# function! s:denite_my_settings() abort
#         nnoremap <silent><buffer><expr> <Esc>
#                  denite#do_map('quit')
#         nnoremap <silent><buffer><expr> <Space>
#                  denite#do_map('toggle_select').'j'
#         nnoremap <silent><buffer><expr> <CR>
#                  denite#do_map('do_action')
#         nnoremap <silent><buffer><expr> o
#                  denite#do_map('do_action')
#         nnoremap <silent><buffer><expr> s
#                  denite#do_map('do_action', 'split')
#         nnoremap <silent><buffer><expr> v
#                  denite#do_map('do_action', 'vsplit')
#         nnoremap <silent><buffer><expr> i
#                  denite#do_map('open_filter_buffer')
#         nnoremap <silent><buffer><expr> ..
#                  denite#do_map('move_up_path')
# endfunction
# """

