# ddu.vim
[[plugins]]
repo = 'Shougo/ddu.vim'
on_event = ["VimEnter"]

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_source = ["ddu.vim"]

# ui
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = ["ddu.vim"]

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = ["ddu.vim"]

# source
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = ["ddu.vim"]

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = ["ddu.vim"]

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = ["ddu.vim"]

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = ["ddu.vim"]

[[plugins]]
repo = 'liquidz/ddu-source-custom-list'
on_source = ["ddu.vim"]

# matcher
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = ["ddu.vim"]

# kind
[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = ["ddu.vim"]
