[[plugins]]
repo = 'Shougo/ddu.vim'
# on_event = ['BufRead', 'CursorHold']
lua_source = '''
    require("configs/ddu")
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

# ===== ddu filter =====
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = "Milly/ddu-filter-kensaku"
on_source = "ddu.vim"

[[plugins]]
repo = "Milly/ddu-filter-merge"
on_source = "ddu.vim"

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = "Shougo/ddu-source-line"
on_source = 'ddu.vim'

[[plugins]]
repo = "shun/ddu-source-buffer"
on_source = 'ddu.vim'

[[plugins]]
repo = "liquidz/ddu-source-custom-list"
on_source = 'ddu.vim'

[[plugins]]
repo = "4513ECHO/ddu-source-source"
on_source = 'ddu.vim'

[[plugins]]
repo = "yuki-yano/ddu-filter-fzf"
on_source = 'ddu.vim'

[[plugins]]
repo = "4513ECHO/ddu-source-ghq"
on_source = 'ddu.vim'

[[plugins]]
repo = "kuuote/ddu-source-mr"
on_source = "ddu.vim"

[[plugins]]
repo = "matsui54/ddu-source-file_external"
on_source = "ddu.vim"

[[plugins]]
repo = "matsui54/ddu-source-help"
on_source = "ddu.vim"

[[plugins]]
repo = "uga-rosa/ddu-source-lsp"
on_source = "ddu.vim"

[[plugins]]
repo = "kuuote/ddu-source-git_diff"
on_source = "ddu.vim"
