[[plugins]]
repo = 'https://github.com/akinsho/flutter-tools.nvim'
on_ft = ["dart"]
lua_source = """
require("flutter-tools").setup{}
"""

[[plugins]]
repo = 'skanehira/command.vim'
on_cmd = ["CommandBufferOpen"]

[[plugins]]
repo = 'andweeb/presence.nvim'
on_event = ["VimEnter"]

[[plugins]]
repo ='p00f/nvim-ts-rainbow'
on_event = ["VimEnter"]

[[plugins]]
repo = 'tpope/vim-commentary'
on_event = ["VimEnter"]

[[plugins]]
repo= 'folke/noice.nvim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
on_event = ["VimEnter"]

# カラースチーム
[[plugins]]
repo = 'sainnhe/everforest'
on_func = ['colorscheme']

[[plugins]]
repo = 'folke/tokyonight.nvim'
on_func = ['colorscheme']

[[plugins]]
repo = 'bfredl/nvim-luadev'
on_cmd = ['Luadev']

# 使用頻度が低いプラグイン
# 毎回使わないようなプラグインはここ
[[plugins]]
repo = 'sakhnik/nvim-gdb'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'bun913/min-todo.vim'

[[plugins]]
repo = 'itchyny/calendar.vim'

[[plugins]]
repo = 'skanehira/translate.vim'
on_event = ['VimEnter']

# マークダウン

[[plugins]]
repo = 'previm/previm'
on_cmd = ['PrevimOpen']

[[plugins]]
repo = 'skanehira/preview-markdown.vim'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'tyru/open-browser.vim'



# ファイル固有
# on_ft推奨

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]]
repo = 'integralist/vim-mypy'

[[plugins]]
repo = 'habamax/vim-rst'
on_ft = ["rst"]

[[plugins]]
repo = 'glench/vim-jinja2-syntax'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ["fish"]

[[plugins]]
repo = 'hisaknown/nanomap.vim'

[[plugins]]
repo = "peterhoeg/vim-qml"
on_ft = ["qml"]

[[plugins]]
repo = "mattn/emmet-vim"
on_ft = ["html"]

[[plugins]]
repo = 'alvan/vim-closetag'
on_event = ['VimEnter']

[[plugins]]
repo = 'skanehira/vsession'
on_cmd = ['SaveSession', 'LoadSession', 'DeleteSession']

[[plugins]]
repo = 'alaviss/nim.nvim'
on_ft = ['nim', 'nims', 'nimble']

[[plugins]]
repo = 'twitvim/twitvim'
on_cmd = [
  "FriendsTwitter"
  "PostToTwitter"
  ]

[[plugins]]
repo = 'kdheepak/lazygit.nvim'
on_cmd = ["LazyGit", "LazyGitConfig", "LazyGitFilter", "LazyGitFilterCurrentFile"]

[[plugins]]
repo = 'https://github.com/Shougo/deol.nvim'
on_cmd = ["Deol"]

[[plugins]]
repo = "evanleck/vim-svelte"
on_ft = ["svelte"]

[[plugins]]
repo = "https://github.com/azadkuh/vim-cmus"
on_cmd = ["Cmus", "CmusCurrent", "CmusPrevious", "CmusPlay", "CmusPause", "CmusStop", "CmusNext"]

[[plugins]]
repo = "https://github.com/ErichDonGubler/vim-nushell"
on_ft = ["nushell"]


[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
# on_event = ["VimEnter"]
on_source = ["telescope.nvim"]

[[plugins]]
repo ='nvim-telescope/telescope.nvim'
on_event = ["VimEnter"]
# on_source = ["telescope-file-browser.nvim"]
lua_source = """
-- To get telescope-file-browser loaded and working with telescope,
-- you need to call load_extension, somewhere after setup function:
require("telescope").load_extension("file_browser")
require("telescope").setup({
		extensions = {
			file_browser = {
				-- theme = "ivy",
				-- disables netrw and use telescope-file-browser in its place
				hijack_netrw = true,
				mappings = {
					["i"] = {
						-- your custom insert mode mappings
					},
					["n"] = {
						-- your custom normal mode mappings
					},
				},
			},
		},
	})
"""

# ddu.vim
[[plugins]]
repo = 'Shougo/ddu.vim'
on_event = ["VimEnter"]

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_source = ["ddu.vim"]

# ui
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = ["ddu.vim"]

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = ["ddu.vim"]

# source
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = ["ddu.vim"]

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = ["ddu.vim"]

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = ["ddu.vim"]

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = ["ddu.vim"]

[[plugins]]
repo = 'liquidz/ddu-source-custom-list'
on_source = ["ddu.vim"]

# matcher
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = ["ddu.vim"]

# kind
[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = ["ddu.vim"]
