[[plugins]]
repo = "https://github.com/rlane/pounce.nvim"

[[plugins]]
repo = "https://github.com/hrsh7th/nvim-insx"
on_event = ["VimEnter"]

[[plugins]]
repo = "https://github.com/dstein64/vim-startuptime"

[[plugins]]
repo ='catppuccin/nvim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'

[[plugins]]
repo = 'https://github.com/jay-babu/mason-null-ls.nvim'

[[plugins]]
repo = 'https://github.com/thinca/vim-splash'

[[plugins]]
repo = 'https://github.com/nvim-lualine/lualine.nvim'

# [[plugins]]
# repo = 'https://github.com/s1n7ax/nvim-react'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'

# [[plugins]]
# repo = 'lukas-reineke/indent-blankline.nvim'

[[plugins]]
repo = 'honza/vim-snippets'

# [[plugins]]
# repo = 'prabirshrestha/asyncomplete.vim'

# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-lsp.vim'

# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-ultisnips.vim'

# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-emoji.vim'

# [[plugins]]
# repo = "prabirshrestha/asyncomplete-file.vim"

# [[plugins]]
# repo = 'rafamadriz/friendly-snippets'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason.nvim'
hook_add = """
source /home/coma/.config/nvim/configs/mason.vim
"""

[[plugins]]
repo= 'williamboman/mason-lspconfig.nvim'

[[plugins]]
repo = "hrsh7th/nvim-cmp"

# [[plugins]]
# repo = 'dmitmel/cmp-vim-lsp'

[[plugins]]
repo = "hrsh7th/cmp-nvim-lsp"

[[plugins]]
repo = 'hrsh7th/cmp-buffer'

[[plugins]]
repo = 'hrsh7th/cmp-path'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'

[[plugins]]
repo = 'hrsh7th/cmp-emoji'

[[plugins]]
repo = "quangnguyen30192/cmp-nvim-ultisnips"

[[plugins]]
repo = "f3fora/cmp-spell"

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'codota/tabnine-nvim'

# [[plugins]]
# repo = "tzachar/cmp-tabnine"

# nvim-cmp
[[plugins]]
repo = "hrsh7th/nvim-cmp"

[[plugins]]
repo = "hrsh7th/cmp-nvim-lsp"

[[plugins]]
repo = 'hrsh7th/cmp-buffer'

[[plugins]]
repo = 'hrsh7th/cmp-path'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'

[[plugins]]
repo = 'quangnguyen30192/cmp-nvim-ultisnips'

[[plugins]]
repo = 'rinx/cmp-skkeleton'

# lsp
[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo= 'williamboman/mason-lspconfig.nvim'

[[plugins]]
repo= 'j-hui/fidget.nvim'

[[plugins]]
repo= 'onsails/lspkind.nvim'

[[plugins]]
repo ='echasnovski/mini.nvim'
rev = 'stable'

[[plugins]]
repo = 'miyakogi/seiya.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

# [[plugins]]
# repo ='dense-analysis/ale'

# Themes
[[plugins]]
repo ='morhetz/gruvbox'

[[plugins]]
repo ='yuttie/comfortable-motion.vim'

# [[plugins]]
# repo ='mattn/vim-molder'

# [[plugins]]
# repo = 'mattn/vim-molder-operations'
# on_source = ['vim-molder']

[[plugins]]
repo ='kana/vim-smartword'

[[plugins]]
repo ='vim-jp/vimdoc-ja'

[[plugins]]
repo ='simeji/winresizer'

[[plugins]]
repo ='nvim-treesitter/nvim-treesitter'

# fonts
[[plugins]]
repo = "nvim-tree/nvim-web-devicons"

[[plugins]]
repo ='nvim-lua/plenary.nvim'

[[plugins]]
repo ='vim-denops/denops.vim'

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'statiolake/vim-quickrun-runner-nvimterm'

[[plugins]]
repo = 'thinca/vim-quickrun'
 on_cmd = ['Quickrun']

[[plugins]]
repo = 'sebdah/vim-delve'

[[plugins]]
repo = "zah/nim.vim"
on_ft = ['nim', 'nims', 'nimble']

[[plugins]]
repo = "https://github.com/segeljakt/vim-silicon"
repo = "Shougo/ddu-ui-filer"

[[plugins]]
repo = 'wakatime/vim-wakatime'

# theme
[[plugins]]
repo = 'sainnhe/gruvbox-material'

[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'

[[plugins]]
repo = 'simnalamburt/vim-mundo'


# SKK
[[plugins]]
repo='vim-skk/denops-skkeleton.vim'
hook_add = """
imap <C-j> <Plug>(skkeleton-toggle)
cmap <C-j> <Plug>(skkeleton-toggle)

call skkeleton#config({
\'eggLikeNewline':v:true
\})
"""