[[plugins]]
repo= 'lilydjwg/colorizer'
on_event = ["BufRead"]

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
on_event = ["VimEnter"]
lua_source = """
-- require("configs/lualine")
"""

[[plugins]]
# on_event = ["InsertEnter"]
on_event = ["VimEnter"]
repo = 'jose-elias-alvarez/null-ls.nvim'
lua_source = """
require("configs/null-ls")
"""

[[plugins]]
repo = 'jay-babu/mason-null-ls.nvim'
on_source = ["null-ls.nvim"]

[[plugins]]
repo = "segeljakt/vim-silicon"
on_cmd = ["Silicon"]
lua_source = """
require("configs/silicon")
"""

[[plugins]]
repo = "mattn/vim-chatgpt"
on_cmd = ["chatgpt", "codereviewplease"]

[[plugins]]
repo = "lambdalisue/kensaku-command.vim"
on_cmd = ["Kensaku"]

[[plugins]]
repo = 'mhanberg/elixir.nvim'
on_ft = ["elixir"]
lua_source = """
-- require("elixir").setup({
--   cmd = "/home/coma/ghq/github.com/elixir-lsp/elixir-ls/release/language_server.sh",
-- })
"""

[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = ["elixir"]

[[plugins]]
repo = 'akinsho/flutter-tools.nvim'
on_ft = ["dart"]
lua_source = """
require("flutter-tools").setup{}
"""

[[plugins]]
repo = 'skanehira/command.vim'
on_cmd = ["CommandBufferOpen"]

[[plugins]]
repo= 'https://github.com/nvim-treesitter/nvim-treesitter'
#on_event = ["BufRead"]
on_event = ["VimEnter"]

[[plugins]]
repo = 'tpope/vim-commentary'
on_event = ["VimEnter"]

[[plugins]]
repo= 'folke/noice.nvim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
on_event = ["VimEnter"]

# カラースチーム
[[plugins]]
repo = 'sainnhe/everforest'
on_func = ['colorscheme']

[[plugins]]
repo = 'folke/tokyonight.nvim'
on_func = ['colorscheme']

[[plugins]]
repo = 'bfredl/nvim-luadev'
on_cmd = ['Luadev']

# 使用頻度が低いプラグイン
# 毎回使わないようなプラグインはここ
[[plugins]]
repo = 'sakhnik/nvim-gdb'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'skanehira/translate.vim'
on_event = ['VimEnter']

# マークダウン

[[plugins]]
repo = 'previm/previm'
on_cmd = ['PrevimOpen']

[[plugins]]
repo = 'skanehira/preview-markdown.vim'

[[plugins]]
repo = 'tpope/vim-markdown'

# ファイル固有
# on_ft推奨

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]]
repo = 'integralist/vim-mypy'

[[plugins]]
repo = 'habamax/vim-rst'
on_ft = ["rst"]


[[plugins]]
repo = 'glench/vim-jinja2-syntax'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ["fish"]

[[plugins]]
repo = 'https://github.com/gleam-lang/gleam.vim'
on_ft = ["gleam"]

[[plugins]]
repo = 'hisaknown/nanomap.vim'

[[plugins]]
repo = "peterhoeg/vim-qml"
on_ft = ["qml"]

[[plugins]]
repo = "mattn/emmet-vim"
on_ft = ["html"]

[[plugins]]
repo = 'alvan/vim-closetag'
on_event = ['VimEnter']

[[plugins]]
repo = 'skanehira/vsession'
on_cmd = ['SaveSession', 'LoadSession', 'DeleteSession']

[[plugins]]
repo = 'alaviss/nim.nvim'
on_ft = ['nim', 'nims', 'nimble']

[[plugins]]
repo = 'twitvim/twitvim'
on_cmd = [
  "FriendsTwitter"
  "PostToTwitter"
  ]

[[plugins]]
repo = 'kdheepak/lazygit.nvim'
on_cmd = ["LazyGit", "LazyGitConfig", "LazyGitFilter", "LazyGitFilterCurrentFile"]

[[plugins]]
repo = 'https://github.com/Shougo/deol.nvim'
on_cmd = ["Deol"]

[[plugins]]
repo = "evanleck/vim-svelte"
on_ft = ["svelte"]

[[plugins]]
repo = "https://github.com/azadkuh/vim-cmus"
on_cmd = ["Cmus", "CmusCurrent", "CmusPrevious", "CmusPlay", "CmusPause", "CmusStop", "CmusNext"]

[[plugins]]
repo = "https://github.com/ErichDonGubler/vim-nushell"
on_ft = ["nushell"]


[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
# on_event = ["VimEnter"]
on_source = ["telescope.nvim"]

[[plugins]]
repo = 'https://github.com/Allianaab2m/telescope-kensaku.nvim'
on_source = ["telescope.nvim"]

[[plugins]]
repo ='nvim-telescope/telescope.nvim'
on_cmd = ["Telescope"]
# on_source = ["telescope-file-browser.nvim"]
lua_source = """
-- To get telescope-file-browser loaded and working with telescope,
-- you need to call load_extension, somewhere after setup function:
require("telescope").load_extension("file_browser")
require("telescope").load_extension("kensaku")

require("telescope").setup({
		extensions = {
			file_browser = {
				-- theme = "ivy",
				-- disables netrw and use telescope-file-browser in its place
				hijack_netrw = true,
				mappings = {
					["i"] = {
						-- your custom insert mode mappings
					},
					["n"] = {
						-- your custom normal mode mappings
					},
				},
			},
		},
	})
"""


[[plugins]]
repo= 'https://github.com/syouzan420/tatevim'
on_cmd = ["Tate"]

[[plugins]]
repo = 'itchyny/calendar.vim'

[[plugins]]
repo = 'https://github.com/dstein64/vim-startuptime'
on_cmd = ["StartupTime"]

[[plugins]]
repo= 'https://github.com/yuttie/comfortable-motion.vim'
on_event = ["BufRead"]

[[plugins]]
repo= 'j-hui/fidget.nvim'

[[plugins]]
repo = 'codota/tabnine-nvim'

[[plugins]]
repo= 'https://github.com/beauwilliams/statusline.lua'
on_event = ["VimEnter"]
lua_source = """
local statusline = require('statusline')
statusline.tabline = false
statusline.lsp_diagnostics = true
statusline.ale_diagnostics = false

vim.o.laststatus=3
"""

[[plugins]]
repo = 'https://github.com/mhinz/vim-sayonara'
on_cmd = ["Sayonara", "Sayonara!"]

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = ["InsertEnter"]

[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'
on_cmd = ["DenopsHello", "DenopsGrep"]

[[plugins]]
repo = 'https://github.com/p00f/nvim-ts-rainbow'
on_event = ["BufRead"]

[[plugins]]
repo = "folke/neodev.nvim"
on_source = ["nvim-cmp"]
lua_source = """
-- IMPORTANT: make sure to setup neodev BEFORE lspconfig
require("neodev").setup({
  -- add any options here, or leave empty to use the default settings
})

-- then setup your lsp server as usual
local lspconfig = require('lspconfig')

-- example to setup lua_ls and enable call snippets
lspconfig.lua_ls.setup({
  settings = {
    Lua = {
      completion = {
        callSnippet = "Replace"
      }
    }
  }
})
"""

[[plugins]]
repo = 'sainnhe/gruvbox-material'
on_event = ["VimEnter"]

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_event = ["VimEnter"]
