# [[plugins]]
# repo = "neoclide/coc.nvim"
# merge = 0
# rev = "release"
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
  let g:coc_global_extensions = ['coc-json', 'coc-css', 'coc-eslint', 'coc-prettier', 'coc-tsserver', 'coc-toml', 'coc-yaml', 'coc-jedi', 'coc-go', 'coc-vimlsp']
  call coc#util#install()
'''

[[plugins]]
repo = 'sainnhe/gruvbox-material'

[[plugins]]
repo = 'miyakogi/seiya.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'kana/vim-smartword'
