[[plugins]]
repo = 'thinca/vim-splash'
on_lua = """
require("configs/splash")
"""

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = "https://github.com/vim-crystal/vim-crystal"

#theme
[[plugins]]
repo = 'sainnhe/gruvbox-material'

[[plugins]]
repo = 'https://github.com/sainnhe/everforest'

[[plugins]]
repo = "https://github.com/morhetz/gruvbox"
