# [[plugins]]
# repo = 'thinca/vim-splash'
# lua_source = """
# -- require("configs/splash")
# """

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = "https://github.com/vim-crystal/vim-crystal"

#theme
[[plugins]]
repo = 'https://github.com/pierrechevalier83/labcoat.nvim'

[[plugins]]
repo = 'sainnhe/gruvbox-material'

[[plugins]]
repo = 'https://github.com/echasnovski/mini.nvim'

[[plugins]]
repo = 'https://github.com/sainnhe/everforest'

[[plugins]]
repo = "https://github.com/morhetz/gruvbox"

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
