[[plugins]]
repo= 'lilydjwg/colorizer'
on_event = ["BufEnter"]

[[plugins]]
on_event = ["BufRead"]
repo = 'jose-elias-alvarez/null-ls.nvim'
lua_source = """
require("configs/null-ls")
"""

[[plugins]]
repo = 'jay-babu/mason-null-ls.nvim'
on_source = ["null-ls.nvim"]

[[plugins]]
repo = "segeljakt/vim-silicon"
on_cmd = ["Silicon"]
lua_source = """
require("configs/silicon")
"""

[[plugins]]
repo = "mattn/vim-chatgpt"
on_cmd = ["chatgpt", "codereviewplease"]

[[plugins]]
repo = "lambdalisue/kensaku-command.vim"
on_cmd = ["Kensaku"]

[[plugins]]
repo = 'skanehira/command.vim'
on_cmd = ["CommandBufferOpen"]

[[plugins]]
repo = 'https://github.com/numToStr/Comment.nvim'
on_event = ["BufRead"]
lua_source = """
require('Comment').setup()
"""

[[plugins]]
repo= 'folke/noice.nvim'

[[plugins]]
repo = "lukas-reineke/indent-blankline.nvim"
# on_event = ["VimEnter"]
lua_source = """
require("configs/blankline")
"""

# カラースチーム
[[plugins]]
repo = 'folke/tokyonight.nvim'
on_func = ['colorscheme']

[[plugins]]
repo = 'bfredl/nvim-luadev'
on_cmd = ['Luadev']

# 使用頻度が低いプラグイン
# 毎回使わないようなプラグインはここ
[[plugins]]
repo = 'sakhnik/nvim-gdb'
on_cmd = [
"GdbStart",
"GdbStartPDB",
"GdbStartBashDB",
"GdbStartRR",
"GdbBreakpointToggle",
"GdbUntil",
"GdbContinue",
"GdbNext",
"GdbStep"
"GdbFinish",
"GdbFrameUp",
"GdbFrameDown"]

[[plugins]]
repo = 'kylechui/nvim-surround'
on_event = ["InsertEnter"]
lua_source = """
require("nvim-surround").setup({})
"""

[[plugins]]
repo = 'skanehira/translate.vim'
on_cmd = ["Translate"]

[[plugins]]
repo = 'alvan/vim-closetag'
on_event = ["InsertEnter"]

[[plugins]]
repo = 'twitvim/twitvim'
on_cmd = [
  "FriendsTwitter"
  "PosttoTwitter"
  ]

[[plugins]]
repo = 'kdheepak/lazygit.nvim'
on_cmd = ["LazyGit", "LazyGitConfig", "LazyGitFilter", "LazyGitFilterCurrentFile"]

[[plugins]]
repo = 'https://github.com/Shougo/deol.nvim'
on_cmd = ["Deol"]
# source_lua = """
# """

[[plugins]]
repo = "https://github.com/azadkuh/vim-cmus"
on_cmd = ["Cmus", "CmusCurrent", "CmusPrevious", "CmusPlay", "CmusPause", "CmusStop", "CmusNext"]

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
on_source = ["telescope.nvim"]

[[plugins]]
repo = 'https://github.com/Allianaab2m/telescope-kensaku.nvim'
on_source = ["telescope.nvim"]

[[plugins]]
repo ='nvim-telescope/telescope.nvim'
on_cmd = ["Telescope"]
# on_source = ["telescope-file-browser.nvim"]
lua_source = """
-- To get telescope-file-browser loaded and working with telescope,
-- you need to call load_extension, somewhere after setup function:
require("telescope").load_extension("file_browser")
require("telescope").load_extension("kensaku")

require("telescope").setup({
		extensions = {
			file_browser = {
				-- theme = "ivy",
				-- disables netrw and use telescope-file-browser in its place
				hijack_netrw = true,
				mappings = {
					["i"] = {
						-- your custom insert mode mappings
					},
					["n"] = {
						-- your custom normal mode mappings
					},
				},
			},
		},
	})
"""


[[plugins]]
repo= 'https://github.com/syouzan420/tatevim'
on_cmd = ["Tate"]

[[plugins]]
repo = 'itchyny/calendar.vim'
on_cmd = ["Calendar"]

[[plugins]]
repo = 'https://github.com/dstein64/vim-startuptime'
on_cmd = ["StartupTime"]

[[plugins]]
repo= 'https://github.com/yuttie/comfortable-motion.vim'
on_event = ["BufRead"]

[[plugins]]
repo = 'https://github.com/mhinz/vim-sayonara'
on_cmd = ["Sayonara", "Sayonara!"]

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = ["InsertEnter"]

[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'
on_cmd = ["DenopsHello", "DenopsGrep"]

[[plugins]]
repo = 'https://github.com/mattreduce/vim-mix'
on_cmd = ["Mix", "Mclean", "Mcompile", "Mdeps", "Mtest"]

[[plugins]]
repo = 'https://github.com/vim-test/vim-test'
on_cmd = ["TestNearest", "TestFile", "TestSuite", "TestLast", "TestVisit"]

[[plugins]]
repo = "https://github.com/wakatime/vim-wakatime"
on_event = ["BufRead"]

[[plugins]]
repo = "https://github.com/HiPhish/nvim-ts-rainbow2"
on_event = ["BufRead"]
lua_source = """
require('nvim-treesitter.configs').setup {
  rainbow = {
    enable = true,
    query = 'rainbow-parens',
    strategy = require('ts-rainbow').strategy.global,
  }
}
"""

[[plugins]]
repo = "https://github.com/JoosepAlviste/nvim-ts-context-commentstring"
on_event = ["InsertEnter"]
lua_source = """
require'nvim-treesitter.configs'.setup {
  context_commentstring = {
    enable = true
  }
}
"""

[[plugins]]
repo= 'https://github.com/nvim-treesitter/nvim-treesitter'
on_event = ["BufRead"]
lua_source = """
require("configs/treesitter")
"""

[[plugins]]
repo = "https://github.com/vim-skk/skkeleton"
on_event = ["InsertEnter"]
lua_source = """
require("configs/skkeleton")
"""

[[plugins]]
repo = "https://github.com/phaazon/hop.nvim"
on_event = ["BufEnter"]
lua_source = """
require("configs/hop")
"""

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'
on_event = ["BufRead"]

[[plugins]]
repo = 'https://github.com/miyakogi/seiya.vim'
on_event = ["BufRead"]

[[plugins]]
repo = "https://github.com/nvim-treesitter/nvim-treesitter-context"
on_event = ["BufRead"]
lua_source = """
require'treesitter-context'.setup{
  enable = true, -- Enable this plugin (Can be enabled/disabled later via commands)
  max_lines = 0, -- How many lines the window should span. Values <= 0 mean no limit.
  min_window_height = 0, -- Minimum editor window height to enable context. Values <= 0 mean no limit.
  line_numbers = true,
  multiline_threshold = 20, -- Maximum number of lines to collapse for a single context line
  trim_scope = 'outer', -- Which context lines to discard if `max_lines` is exceeded. Choices: 'inner', 'outer'
  mode = 'cursor',  -- Line used to calculate context. Choices: 'cursor', 'topline'
  -- Separator between context and content. Should be a single character string, like '-'.
  -- When separator is set, the context will only show up when there are at least 2 lines above cursorline.
  separator = nil,
  zindex = 20, -- The Z-index of the context window
}
"""

[[plugins]]
repo = "https://github.com/lambdalisue/fern.vim"
on_cmd = ["Fern"]
lua_source = """
vim.cmd("let g:fern#renderer = 'nerdfont'")
"""

[[plugins]]
repo = "lambdalisue/fern-renderer-nerdfont.vim"
on_source = ["fern.vim"]

[[plugins]]
repo = "lambdalisue/nerdfont.vim"
on_source = ["fern.vim"]

[[plugins]]
repo = "~/ghq/github.com/coma/runit.nvim"
on_event = ["BufRead"]
lua_source = """
require("configs/runit")
"""

[[plugins]]
repo = "https://github.com/Shougo/dda.vim"
on_event = ["BufRead"]

[[plugins]]
repo = "junegunn/fzf.vim"
on_cmd = ["Fq"]

[[plugins]]
repo = 'simrat39/symbols-outline.nvim'
on_event = ["VimEnter"]
lua_source = """
require("configs/outline")
vim.cmd("au BufRead * :SymbolsOutlineOpen")
"""

[[plugins]]
repo = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects"
on_source = ["nvim-treesitter"]

[[plugins]]
repo = "https://github.com/SmiteshP/nvim-navic"
on_event = ["VimEnter"]
lua_source = """
local navic = require("nvim-navic")

navic.setup {
    icons = {
        File          = " ",
        Module        = " ",
        Namespace     = " ",
        Package       = " ",
        Class         = " ",
        Method        = " ",
        Property      = " ",
        Field         = " ",
        Constructor   = " ",
        Enum          = "練",
        Interface     = "練",
        Function      = " ",
        Variable      = " ",
        Constant      = " ",
        String        = " ",
        Number        = " ",
        Boolean       = "◩ ",
        Array         = " ",
        Object        = " ",
        Key           = " ",
        Null          = "ﳠ ",
        EnumMember    = " ",
        Struct        = " ",
        Event         = " ",
        Operator      = " ",
        TypeParameter = " ",
    },
    lsp = {
        auto_attach = false,
        preference = nil,
    },
    highlight = false,
    separator = " > ",
    depth_limit = 0,
    depth_limit_indicator = "..",
    safe_output = true
}

"""

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
on_event = ["VimEnter"]
lua_source = """
require("configs/lualine")
"""

[[plugins]]
repo = 'https://github.com/simeji/winresizer'
on_event = ["BufEnter"]

[[plugins]]
repo = 'https://github.com/utilyre/barbecue.nvim'
on_source = ["nvim-navic"]
# on_event = ["BufEnter"]
lua_source = """
require("configs/barbecue")
"""
