[[plugins]]
repo = 'vim-denops/denops.vim'
hook_source = """
let g:denops#deno = exepath("deno")
"""

[[plugins]]
repo = "nvim-lua/plenary.nvim"

# dpp.vim
[[plugins]]
repo = "Shougo/dpp.vim"

[[plugins]]
repo = "Shougo/dpp-ext-local"

[[plugins]]
repo = "Shougo/dpp-ext-toml"

[[plugins]]
repo = "Shougo/dpp-ext-lazy"

[[plugins]]
repo = "Shougo/dpp-ext-installer"

[[plugins]]
repo = "Shougo/dpp-protocol-git"

[[plugins]]
repo = "https://github.com/folke/snacks.nvim"

[[plugins]]
repo = 'https://github.com/tkmpypy/chowcho.nvim'
lua_add = '''
require('chowcho').setup {
  labels = { "A", "S", "D", "F", "G", "H", "K", "L", },
  ignore_case = true
}
'''
