# ファイル固有
# on_ft推奨

[[plugins]]
repo = 'mhanberg/elixir.nvim'
on_ft = ["elixir", "eex", "heex", "surface"]
lua_source = """
-- require("elixir").setup({
--   cmd = "/home/coma/ghq/github.com/elixir-lsp/elixir-ls/release/language_server.sh",
-- })
"""

[[plugins]]
repo = 'akinsho/flutter-tools.nvim'
on_ft = ["dart"]
lua_source = """
require("flutter-tools").setup{}
"""

[[plugins]]
repo = 'habamax/vim-rst'
on_ft = ["rst"]

[[plugins]]
repo = 'glench/vim-jinja2-syntax'

[[plugins]]
repo = 'dag/vim-fish'
# on_ft = ["fish"]

[[plugins]]
repo = 'https://github.com/gleam-lang/gleam.vim'
on_ft = ["gleam"]

[[plugins]]
repo = "peterhoeg/vim-qml"
on_ft = ["qml"]

[[plugins]]
repo = "mattn/emmet-vim"
on_ft = [
	    "html",
	    "css",
	    'xml',
	    'typescriptreact',
	    'javascriptreact',
	    'css',
	    'sass',
	    'scss',
	    'less',
	    'heex',
	    'tsx',
	    'jsx',
	    'astro']
lua_source = """
-- vim.g.user_emmet_leader_key='<Leader>'

vim.g.user_emmet_settings = {
  variables = {lang = 'ja'},
}
"""

[[plugins]]
repo = 'alaviss/nim.nvim'
on_ft = ['nim', 'nims', 'nimble']

[[plugins]]
repo = "evanleck/vim-svelte"
on_ft = ["svelte"]

[[plugins]]
repo = "https://github.com/ErichDonGubler/vim-nushell"
on_ft = ["nushell"]

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ["svelte"]

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ["svelte"]

[[plugins]]
repo = 'https://github.com/ziglang/zig.vim'
on_ft = ["zig"]

[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = ["elixir"]

# マークダウン
[[plugins]]
repo = 'previm/previm'
on_cmd = ['PrevimOpen']

[[plugins]]
repo = 'skanehira/preview-markdown.vim'
on_ft = ["markdown"]

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ["markdown"]

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ["jsx", "tsx"]

[[plugins]]
repo = 'integralist/vim-mypy'
on_ft = ["python"]

[[plugins]]
repo = 'https://github.com/lark-parser/vim-lark-syntax'
on_ft = ["lark"]

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ["rust"]

[[plugins]]
repo = 'https://github.com/cotowali/vim-cotowali'
on_ft = ["cotowali"]

[[plugins]]
repo = 'ollykel/v-vim'
on_ft = ["cotowali", "v", "vsh"]

[[plugins]]
repo = "https://github.com/vim-crystal/vim-crystal"
on_ft = ["crystal"]

[[plugins]]
repo = 'jdonaldson/vaxe'
on_ft = ["haxe"]

[[plugins]]
repo = 'teal-language/vim-teal'
on_ft = ["teal"]

[[plugins]]
repo = "https://github.com/wuelnerdotexe/vim-astro"
on_ft = ["astro"]
