[[plugins]]
repo = 'neovim/nvim-lspconfig'
# on_event = ['BufEnter']
on_event = ['BufRead', 'CursorHold']
lua_source = """
require("configs/lsp")
"""
# on_event = ['LspAttach']

# Add `vim.*` in LSP suggestion
[[plugins]]
repo = 'folke/lazydev.nvim'
on_source = 'nvim-lspconfig'

# Language Server management
[[plugins]]
repo = 'williamboman/mason.nvim'
on_event = ['BufRead', 'CursorHold']
lua_source = """
require("mason").setup()
"""

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'mason.nvim'
lua_source = """
require("mason-lspconfig").setup_handlers({
	function(server_name)
		-- require("lspconfig")[server_name].setup({})
		vim.lsp.enable(server_name)
	end,
})
"""
