# dpp.vim
[[plugins]]
repo = 'Shougo/dpp.vim'

[[plugins]]
repo = "Shougo/dpp-ext-toml"

[[plugins]]
repo = "Shougo/dpp-ext-lazy"

[[plugins]]
repo = "Shougo/dpp-ext-installer"

[[plugins]]
repo = "Shougo/dpp-protocol-git"

[[plugins]]
repo = "vim-jp/vital.vim"

[[plugins]]
repo = 'lambdalisue/kensaku.vim'

# denops.vim
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'jxnblk/vim-mdx-js'

[[plugins]]
repo = 'mattn/vim-molder'
hook_add = '''
let g:molder_show_hidden = 1

autocmd FileType molder call s:molder_settings()
function! s:molder_settings() abort
  nnoremap <buffer><silent> l
    \ <Cmd>call molder#open()<CR> 

  nnoremap <buffer><silent> K
    \ <Cmd>call molder#extension#operations#newdir_parents()<CR> 

  nnoremap <buffer><silent> R
    \ <Cmd>call molder#extension#operations#rename()<CR>

  nnoremap <buffer><silent> D
    \ <Cmd>call molder#extension#operations#delete()<CR>

  nnoremap <buffer><silent> N
    \ <Cmd>call molder#extension#operations#newfile()<CR>
endfunction
'''

[[plugins]]
repo = 'mattn/vim-molder-operations'

[[plugins]]
repo = 'comamoca/additional-molder-operations'
