[[plugins]]
repo = 'liquidz/dps-parinfer'
on_ft = ['clojure', 'lisp', 'fennel', 'janet', 'hy']

[[plugins]]
repo = 'zah/nim.vim'
on_ft = 'nim'

[[plugins]]
repo = 'janet-lang/janet.vim'
on_ft = 'janet'
hook_source = '''
autocmd FileType janet setlocal sw=2 sts=2 ts=2 et
'''

[[plugins]]
repo = 'lark-parser/vim-lark-syntax'
on_ft = 'lark'

[[plugins]]
repo = 'gleam-lang/gleam.vim'
on_ft = 'gleam'

[[plugins]]
repo = 'vmchale/dhall-vim'
on_ft = 'dhall'

[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = ['elixir', 'heex']

[[plugins]]
repo = 'mattn/vim-maketable'
on_ft = 'markdown'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = 'markdown'

[[plugins]]
repo = 'DrTom/fsharp-vim'
on_ft = 'fsharp'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['jsx']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html']

[[plugins]]
repo = 'rescript-lang/vim-rescript'
on_ft = ['rescript']

[[plugins]]
repo = 'jdonaldson/vaxe'
on_ft = ['haxe']

# [[plugins]]
# repo = 'kovisoft/slimv'
# on_ft = ['lisp']

[[plugins]]
repo = 'fukamachi/vlime'
on_ft = ['lisp']
rtp = "vim/"
hook_source = '''
nnoremap <silent> <LocalLeader>rr :call VlimeStart()<CR>

let g:vlime_cl_impl = "mondo"
let g:vlime_cl_use_terminal = v:true
let g:vlime_window_settings = {'server': {'pos': 'botright', 'size': v:null, 'vertical': v:true}}

function! VlimeBuildServerCommandFor_mondo(vlime_loader, vlime_eval)
    return ["mondo", "--server", "vlime"]
endfunction

function! VlimeStart()
    call vlime#server#New(v:true, get(g:, "vlime_cl_use_terminal", v:false))
endfunction
'''
