[[plugins]]
repo = 'liquidz/dps-parinfer'
on_ft = ['clojure', 'lisp', 'fennel', 'janet', 'hy']

[[plugins]]
repo = 'zah/nim.vim'
on_ft = 'nim'

[[plugins]]
repo = 'janet-lang/janet.vim'
on_ft = 'janet'
hook_source = '''
autocmd FileType janet setlocal sw=2 sts=2 ts=2 et
'''

[[plugins]]
repo = 'lark-parser/vim-lark-syntax'
on_ft = 'lark'

[[plugins]]
repo = 'gleam-lang/gleam.vim'
on_ft = 'gleam'

[[plugins]]
repo = 'vmchale/dhall-vim'
on_ft = 'dhall'

[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = ['elixir', 'heex']

[[plugins]]
repo = 'mattn/vim-maketable'
on_ft = 'markdown'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = 'markdown'

[[plugins]]
repo = 'DrTom/fsharp-vim'
on_ft = 'fsharp'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['jsx']
