# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aider = {
    pname = "aider";
    version = "1d3d396aa81445543855364da62787a2c3f40d70";
    src = fetchFromGitHub {
      owner = "tninja";
      repo = "aider.el";
      rev = "1d3d396aa81445543855364da62787a2c3f40d70";
      fetchSubmodules = false;
      sha256 = "sha256-pzoNIMV9zDdHipToegUKvDTWo19/AV/oWYyM/ZOB0i4=";
    };
    date = "2025-03-24";
  };
  copilot = {
    pname = "copilot";
    version = "7d105d708a23d16cdfd5240500be8bb02f95a46e";
    src = fetchFromGitHub {
      owner = "copilot-emacs";
      repo = "copilot.el";
      rev = "7d105d708a23d16cdfd5240500be8bb02f95a46e";
      fetchSubmodules = false;
      sha256 = "sha256-ATIyNAnd1pU82xdGH7+z9zkOcDVJhYhh65QDQ73NiL0=";
    };
    date = "2025-02-23";
  };
  digs = {
    pname = "digs";
    version = "7b6a0776ced84e868556a2c9711e5637e9fb9b88";
    src = fetchFromGitHub {
      owner = "zonuexe";
      repo = "digs.el";
      rev = "7b6a0776ced84e868556a2c9711e5637e9fb9b88";
      fetchSubmodules = false;
      sha256 = "sha256-2mj6wngnU8wohC0fyFdbOswdTDqvYSBVTtwu4r2ooHQ=";
    };
    date = "2025-02-17";
  };
  eglot-booster = {
    pname = "eglot-booster";
    version = "e6daa6bcaf4aceee29c8a5a949b43eb1b89900ed";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/jdtsmith/eglot-booster/refs/heads/main/eglot-booster.el";
      sha256 = "sha256-MGMKFtivqM979xf2H0XinLvlVhp23Ynd1+UqTxD3eZY=";
    };
    date = "2024-10-29";
  };
  emacs_fancy_logos = {
    pname = "emacs_fancy_logos";
    version = "d37f57854fb1fab379cf5c39a7c554f4e23f1801";
    src = fetchFromGitHub {
      owner = "egstatsml";
      repo = "emacs_fancy_logos";
      rev = "d37f57854fb1fab379cf5c39a7c554f4e23f1801";
      fetchSubmodules = false;
      sha256 = "sha256-BirkM+QDsmCFZWQAiA7vN4dJ/NNyYDDMwO8VZ5hBD54=";
    };
    date = "2023-04-23";
  };
  folding-mode = {
    pname = "folding-mode";
    version = "c3912c738cf0515f65162479c55999e2992afce5";
    src = fetchFromGitHub {
      owner = "magnars";
      repo = "fold-this.el";
      rev = "c3912c738cf0515f65162479c55999e2992afce5";
      fetchSubmodules = false;
      sha256 = "sha256-j0UtxYMfctJMkdXFlgE+L97jACgQINXXdGB6ucSfzjI=";
    };
    date = "2019-11-07";
  };
  gleam-mode = {
    pname = "gleam-mode";
    version = "75b5b1a2eede31969a94322f117b0c82036ff40b";
    src = fetchFromGitHub {
      owner = "gleam-lang";
      repo = "gleam-mode";
      rev = "75b5b1a2eede31969a94322f117b0c82036ff40b";
      fetchSubmodules = false;
      sha256 = "sha256-pFG4NjFlYdGsulUwbujA01w1gHt+U67fYvFLNdN5RYg=";
    };
    date = "2025-02-23";
  };
  hydra-posframe = {
    pname = "hydra-posframe";
    version = "142a04dd588af6c725e331863c3ca7bd5dda13ec";
    src = fetchFromGitHub {
      owner = "Ladicle";
      repo = "hydra-posframe";
      rev = "142a04dd588af6c725e331863c3ca7bd5dda13ec";
      fetchSubmodules = false;
      sha256 = "sha256-9nVBnpaWZIYNDvS2WWBED0HsIRIv4AR4as6wEe463tI=";
    };
    date = "2023-07-17";
  };
  kdl-ts-mode = {
    pname = "kdl-ts-mode";
    version = "3dbf116cd19261d8d70f456ae3385e1d20208452";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/dataphract/kdl-ts-mode/refs/heads/main/kdl-ts-mode.el";
      sha256 = "sha256-NGC3Fecf9fzw0Gp64afagKCe+4tObXjjkzwtA+L6YKs=";
    };
    date = "2024-01-05";
  };
  ob-ledger = {
    pname = "ob-ledger";
    version = "c2ebeea6f68f2ef804d387c238e4acccf655dc64";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/tkf/org-mode/refs/heads/master/lisp/ob-ledger.el";
      sha256 = "sha256-BleW3N4NljKh9mFD/BpyVI1VPO0E9aODC8vH8gFk7KI=";
    };
    date = "2012-11-06";
  };
  org-bullets = {
    pname = "org-bullets";
    version = "b70ac2ec805bcb626a6e39ea696354577c681b36";
    src = fetchFromGitHub {
      owner = "sabof";
      repo = "org-bullets";
      rev = "b70ac2ec805bcb626a6e39ea696354577c681b36";
      fetchSubmodules = false;
      sha256 = "sha256-HODL+qhUFRjGwHnbEu9Z2Xof9zVT1Wc2pQtb56Qm2YI=";
    };
    date = "2014-09-18";
  };
  org-modern-indent = {
    pname = "org-modern-indent";
    version = "fcd4368476a9c4eadfac4d6f51159d90a15de15a";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "org-modern-indent";
      rev = "fcd4368476a9c4eadfac4d6f51159d90a15de15a";
      fetchSubmodules = false;
      sha256 = "sha256-obx83T90LoVor5O5bniXCtWhNV7GmF3fYpNhCNgSm1M=";
    };
    date = "2025-03-23";
  };
  python-mode = {
    pname = "python-mode";
    version = "1652ed5e650accdf87611814f35907c9da4a47f6";
    src = fetchFromGitHub {
      owner = "emacsmirror";
      repo = "python-mode";
      rev = "1652ed5e650accdf87611814f35907c9da4a47f6";
      fetchSubmodules = false;
      sha256 = "sha256-XCX0HMZrNt3GPJCQ11vVMV2ieqza2EvoMDLbGpT7JVQ=";
    };
    date = "2025-02-23";
  };
  scroll-page-without-moving-point = {
    pname = "scroll-page-without-moving-point";
    version = "835d8df947841bf9acf3da70a015ea1b4e143acd";
    src = fetchFromGitHub {
      owner = "tanrax";
      repo = "scroll-page-without-moving-point.el";
      rev = "835d8df947841bf9acf3da70a015ea1b4e143acd";
      fetchSubmodules = false;
      sha256 = "sha256-d4S7eLAh8YhmiONdd+wKj24lxmvMG+fSGA64lVdrj+c=";
    };
    date = "2024-01-14";
  };
  skk-capf = {
    pname = "skk-capf";
    version = "b2aa36d5fec2ac3cea2cf9dede8f7200efc7570a";
    src = fetchFromGitHub {
      owner = "myuhe";
      repo = "skk-capf";
      rev = "b2aa36d5fec2ac3cea2cf9dede8f7200efc7570a";
      fetchSubmodules = false;
      sha256 = "sha256-IVkEFRwV2SaIH4xVnTqm2YtNeQ08G2GEiPF9+Kgj3Cc=";
    };
    date = "2024-09-23";
  };
  slite = {
    pname = "slite";
    version = "0369de89f273a6aec1ecf93ccb46fcbea5ff2d55";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/tdrhq/slite/refs/heads/main/slite.el";
      sha256 = "sha256-ibi3H4Jk9ShV/UKborSmhCBtORL6ycLPN2gDzyx943c=";
    };
    date = "2025-03-07";
  };
  typst-mode = {
    pname = "typst-mode";
    version = "5776fd4f3608350ff6a2b61b118d38165d342aa3";
    src = fetchFromGitHub {
      owner = "Ziqi-Yang";
      repo = "typst-mode.el";
      rev = "5776fd4f3608350ff6a2b61b118d38165d342aa3";
      fetchSubmodules = false;
      sha256 = "sha256-mqkcNDgx7lc6kUSFFwSATRT+UcOglkeu+orKLiU9Ldg=";
    };
    date = "2023-09-25";
  };
  typst-preview = {
    pname = "typst-preview";
    version = "5719d0fcc624e7910a105bd8eefd2b10bf92a0bf";
    src = fetchFromGitHub {
      owner = "havarddj";
      repo = "typst-preview.el";
      rev = "5719d0fcc624e7910a105bd8eefd2b10bf92a0bf";
      fetchSubmodules = false;
      sha256 = "sha256-r8o90SYFShPLNetLLALrP47jd8PQccvnXCJbKrF9fpk=";
    };
    date = "2025-03-17";
  };
  typst-ts-mode = {
    pname = "typst-ts-mode";
    version = "1367003e2ad55a2f6f9e43178584683028ab56e9";
    src = fetchgit {
      url = "https://git.sr.ht/~meow_king/typst-ts-mode";
      rev = "1367003e2ad55a2f6f9e43178584683028ab56e9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0RAJ/Td3G7FDvzf7t8csNs/uc07WUPGvMo8ako5iyl0=";
    };
    date = "2024-12-07";
  };
}
