# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aider = {
    pname = "aider";
    version = "ac10526c5cfcc2f4288d3539853ff23f4ee7f915";
    src = fetchFromGitHub {
      owner = "tninja";
      repo = "aider.el";
      rev = "ac10526c5cfcc2f4288d3539853ff23f4ee7f915";
      fetchSubmodules = false;
      sha256 = "sha256-45TX5g874ZWq8pAi/bU82SuyWvAbYn31LI2ECqLKXOA=";
    };
    date = "2026-01-10";
  };
  claude-code = {
    pname = "claude-code";
    version = "4a9914bd4161eb43f489820f9174c62390e5adc8";
    src = fetchFromGitHub {
      owner = "stevemolitor";
      repo = "claude-code.el";
      rev = "4a9914bd4161eb43f489820f9174c62390e5adc8";
      fetchSubmodules = false;
      sha256 = "sha256-ISlD6q1hceckry1Jd19BX1MfobHJxng5ulX2gq9f644=";
    };
    date = "2025-12-18";
  };
  claude-shell = {
    pname = "claude-shell";
    version = "8e9e7e22b6fab50e19b293d1ebcf435ad937a41f";
    src = fetchFromGitHub {
      owner = "arminfriedl";
      repo = "claude-shell";
      rev = "8e9e7e22b6fab50e19b293d1ebcf435ad937a41f";
      fetchSubmodules = false;
      sha256 = "sha256-1j1QJJLneLnVJbym5FbSVIKPt91jeg5kNcA3cju+8QM=";
    };
    date = "2024-11-30";
  };
  claudemacs = {
    pname = "claudemacs";
    version = "41c5da556548e220f641fae994bc5110e8c65858";
    src = fetchFromGitHub {
      owner = "cpoile";
      repo = "claudemacs";
      rev = "41c5da556548e220f641fae994bc5110e8c65858";
      fetchSubmodules = false;
      sha256 = "sha256-j7ypcsvdKPaawmzh+1l4ZabILODNqNYOgJ+62PjeJHs=";
    };
    date = "2026-01-16";
  };
  copilot = {
    pname = "copilot";
    version = "7ee4758bb748beac7d29e62de5d2e752ebafb858";
    src = fetchFromGitHub {
      owner = "copilot-emacs";
      repo = "copilot.el";
      rev = "7ee4758bb748beac7d29e62de5d2e752ebafb858";
      fetchSubmodules = false;
      sha256 = "sha256-jzrf6k9yJEMR0H1hOkf1LY2p5ik++poMoAlrhrYPD2U=";
    };
    date = "2025-12-10";
  };
  digs = {
    pname = "digs";
    version = "7b6a0776ced84e868556a2c9711e5637e9fb9b88";
    src = fetchFromGitHub {
      owner = "zonuexe";
      repo = "digs.el";
      rev = "7b6a0776ced84e868556a2c9711e5637e9fb9b88";
      fetchSubmodules = false;
      sha256 = "sha256-2mj6wngnU8wohC0fyFdbOswdTDqvYSBVTtwu4r2ooHQ=";
    };
    date = "2025-02-17";
  };
  eca = {
    pname = "eca";
    version = "298849d1aae3241bf8828b6558c6deb45d75a3c8";
    src = fetchgit {
      url = "https://github.com/editor-code-assistant/eca-emacs";
      rev = "298849d1aae3241bf8828b6558c6deb45d75a3c8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-QpJGTDfvFzCvDmmB8YZ7xEI2d9EiDc7nJDe5k7TUEUA=";
    };
    date = "2026-01-21";
  };
  eglot-booster = {
    pname = "eglot-booster";
    version = "cab7803c4f0adc7fff9da6680f90110674bb7a22";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "eglot-booster";
      rev = "cab7803c4f0adc7fff9da6680f90110674bb7a22";
      fetchSubmodules = false;
      sha256 = "sha256-xUBQrQpw+JZxcqT1fy/8C2tjKwa7sLFHXamBm45Fa4Y=";
    };
    date = "2025-07-16";
  };
  emacs_fancy_logos = {
    pname = "emacs_fancy_logos";
    version = "d37f57854fb1fab379cf5c39a7c554f4e23f1801";
    src = fetchFromGitHub {
      owner = "egstatsml";
      repo = "emacs_fancy_logos";
      rev = "d37f57854fb1fab379cf5c39a7c554f4e23f1801";
      fetchSubmodules = false;
      sha256 = "sha256-BirkM+QDsmCFZWQAiA7vN4dJ/NNyYDDMwO8VZ5hBD54=";
    };
    date = "2023-04-23";
  };
  folding-mode = {
    pname = "folding-mode";
    version = "c3912c738cf0515f65162479c55999e2992afce5";
    src = fetchFromGitHub {
      owner = "magnars";
      repo = "fold-this.el";
      rev = "c3912c738cf0515f65162479c55999e2992afce5";
      fetchSubmodules = false;
      sha256 = "sha256-j0UtxYMfctJMkdXFlgE+L97jACgQINXXdGB6ucSfzjI=";
    };
    date = "2019-11-07";
  };
  gerbil = {
    pname = "gerbil";
    version = "b3417266a8a76dd63b0b870ba600bb8a9ec308ad";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/mighty-gerbils/gerbil/refs/heads/master/etc/gerbil-mode.el";
      sha256 = "sha256-P1nRW6roc6Kr27Un744FF8KL/ihSCiw8K2WpnzxtZq8=";
    };
    date = "2025-12-17";
  };
  gleam-mode = {
    pname = "gleam-mode";
    version = "91cf073c5fb889c091b1797f44cc52419b7c9ae2";
    src = fetchFromGitHub {
      owner = "gleam-lang";
      repo = "gleam-mode";
      rev = "91cf073c5fb889c091b1797f44cc52419b7c9ae2";
      fetchSubmodules = false;
      sha256 = "sha256-EVuEVzjlHg5d9RG69KQGm4T/BnBjzb2X7RRnuKnHpzU=";
    };
    date = "2025-11-06";
  };
  hydra-posframe = {
    pname = "hydra-posframe";
    version = "142a04dd588af6c725e331863c3ca7bd5dda13ec";
    src = fetchFromGitHub {
      owner = "Ladicle";
      repo = "hydra-posframe";
      rev = "142a04dd588af6c725e331863c3ca7bd5dda13ec";
      fetchSubmodules = false;
      sha256 = "sha256-9nVBnpaWZIYNDvS2WWBED0HsIRIv4AR4as6wEe463tI=";
    };
    date = "2023-07-17";
  };
  kdl-ts-mode = {
    pname = "kdl-ts-mode";
    version = "3dbf116cd19261d8d70f456ae3385e1d20208452";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/dataphract/kdl-ts-mode/refs/heads/main/kdl-ts-mode.el";
      sha256 = "sha256-NGC3Fecf9fzw0Gp64afagKCe+4tObXjjkzwtA+L6YKs=";
    };
    date = "2024-01-05";
  };
  lspx = {
    pname = "lspx";
    version = "1b9649fa5567ef482dc54519943737922ef291dd";
    src = fetchFromGitHub {
      owner = "thefrontside";
      repo = "lspx";
      rev = "1b9649fa5567ef482dc54519943737922ef291dd";
      fetchSubmodules = false;
      sha256 = "sha256-RuwtILZ66ztUpxu8UBpwfqMdzmQ26PuSblMJEHKfkqI=";
    };
    date = "2025-11-08";
  };
  mcp = {
    pname = "mcp";
    version = "2e947d2ddc8cbe655f846e23711e412d41f1bf6a";
    src = fetchFromGitHub {
      owner = "lizqwerscott";
      repo = "mcp.el";
      rev = "2e947d2ddc8cbe655f846e23711e412d41f1bf6a";
      fetchSubmodules = false;
      sha256 = "sha256-Cb7G8d2v1l0VghUSPBKFJo7J0hKtPRnIhULzGUBp27s=";
    };
    date = "2026-01-21";
  };
  ob-ledger = {
    pname = "ob-ledger";
    version = "c2ebeea6f68f2ef804d387c238e4acccf655dc64";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/tkf/org-mode/refs/heads/master/lisp/ob-ledger.el";
      sha256 = "sha256-BleW3N4NljKh9mFD/BpyVI1VPO0E9aODC8vH8gFk7KI=";
    };
    date = "2012-11-06";
  };
  org-bullets = {
    pname = "org-bullets";
    version = "b70ac2ec805bcb626a6e39ea696354577c681b36";
    src = fetchFromGitHub {
      owner = "sabof";
      repo = "org-bullets";
      rev = "b70ac2ec805bcb626a6e39ea696354577c681b36";
      fetchSubmodules = false;
      sha256 = "sha256-HODL+qhUFRjGwHnbEu9Z2Xof9zVT1Wc2pQtb56Qm2YI=";
    };
    date = "2014-09-18";
  };
  org-modern-indent = {
    pname = "org-modern-indent";
    version = "ebf9a8e571db523dc6e4cd9ed80d0e0626983ae4";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "org-modern-indent";
      rev = "ebf9a8e571db523dc6e4cd9ed80d0e0626983ae4";
      fetchSubmodules = false;
      sha256 = "sha256-+q7KmbU8A+uR61BSa528vYbdFSj2WGsFWYW/5q7J9Kw=";
    };
    date = "2026-01-02";
  };
  python-mode = {
    pname = "python-mode";
    version = "02b92f2d903d357800a31903f69834ec54cda39b";
    src = fetchFromGitHub {
      owner = "emacsmirror";
      repo = "python-mode";
      rev = "02b92f2d903d357800a31903f69834ec54cda39b";
      fetchSubmodules = false;
      sha256 = "sha256-tiR3qOFsbbbNiebaQyOB/Yn+bZ2wJGaPm6Fpt/IX+Gk=";
    };
    date = "2025-12-15";
  };
  quickrun = {
    pname = "quickrun";
    version = "9199e222f95104ee83e115a9d5ac159d86816706";
    src = fetchFromGitHub {
      owner = "emacsorphanage";
      repo = "quickrun";
      rev = "9199e222f95104ee83e115a9d5ac159d86816706";
      fetchSubmodules = false;
      sha256 = "sha256-VC9BRHCMnn+bw5VytGelTtCo7Y6tOniJYDtZAOAdp0U=";
    };
    date = "2026-01-04";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "f40ece58df8b2f0fb6c8576b527755a552a5e763";
    src = fetchFromGitHub {
      owner = "Fanael";
      repo = "rainbow-delimiters";
      rev = "f40ece58df8b2f0fb6c8576b527755a552a5e763";
      fetchSubmodules = false;
      sha256 = "sha256-JcNRW0+L65NtOBronwyT7SHP9QsNa3ysj4cHv88yfoI=";
    };
    date = "2023-08-30";
  };
  scroll-page-without-moving-point = {
    pname = "scroll-page-without-moving-point";
    version = "a7344713c61d32339162df50ed7d77d11d5b3505";
    src = fetchFromGitHub {
      owner = "tanrax";
      repo = "scroll-page-without-moving-point.el";
      rev = "a7344713c61d32339162df50ed7d77d11d5b3505";
      fetchSubmodules = false;
      sha256 = "sha256-JhaoGq8NSMQzpSm7PIEIO5nC+ngJOXvBviuaCKba9xQ=";
    };
    date = "2025-12-18";
  };
  skk-capf = {
    pname = "skk-capf";
    version = "b2aa36d5fec2ac3cea2cf9dede8f7200efc7570a";
    src = fetchFromGitHub {
      owner = "myuhe";
      repo = "skk-capf";
      rev = "b2aa36d5fec2ac3cea2cf9dede8f7200efc7570a";
      fetchSubmodules = false;
      sha256 = "sha256-IVkEFRwV2SaIH4xVnTqm2YtNeQ08G2GEiPF9+Kgj3Cc=";
    };
    date = "2024-09-23";
  };
  slite = {
    pname = "slite";
    version = "0369de89f273a6aec1ecf93ccb46fcbea5ff2d55";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/tdrhq/slite/refs/heads/main/slite.el";
      sha256 = "sha256-ibi3H4Jk9ShV/UKborSmhCBtORL6ycLPN2gDzyx943c=";
    };
    date = "2025-03-07";
  };
  smartchr = {
    pname = "smartchr";
    version = "b2410de732484030758f72b07e619cc594e6d287";
    src = fetchFromGitHub {
      owner = "imakado";
      repo = "emacs-smartchr";
      rev = "b2410de732484030758f72b07e619cc594e6d287";
      fetchSubmodules = false;
      sha256 = "sha256-3f8oQR4/9WnzD5ds6F7odAaiF8WAzt04WnaZ2c2Qk3c=";
    };
    date = "2022-06-06";
  };
  smudge = {
    pname = "smudge";
    version = "dcca1b9ac15886060788df83c7da63faa5ae027f";
    src = fetchFromGitHub {
      owner = "danielfm";
      repo = "smudge";
      rev = "dcca1b9ac15886060788df83c7da63faa5ae027f";
      fetchSubmodules = false;
      sha256 = "sha256-pwL9S+pZFrzlg07ZHL3kBQwa6SRcc++YlEseZrwDeVo=";
    };
    date = "2025-12-24";
  };
  typst-mode = {
    pname = "typst-mode";
    version = "5776fd4f3608350ff6a2b61b118d38165d342aa3";
    src = fetchFromGitHub {
      owner = "Ziqi-Yang";
      repo = "typst-mode.el";
      rev = "5776fd4f3608350ff6a2b61b118d38165d342aa3";
      fetchSubmodules = false;
      sha256 = "sha256-mqkcNDgx7lc6kUSFFwSATRT+UcOglkeu+orKLiU9Ldg=";
    };
    date = "2023-09-25";
  };
  typst-preview = {
    pname = "typst-preview";
    version = "c685857f2d61133fc268509b39796b2718728f29";
    src = fetchFromGitHub {
      owner = "havarddj";
      repo = "typst-preview.el";
      rev = "c685857f2d61133fc268509b39796b2718728f29";
      fetchSubmodules = false;
      sha256 = "sha256-+426otCa0TASEo9Z+2yH8SUJIGtGEdl35/BdmfBBDbA=";
    };
    date = "2025-11-10";
  };
  typst-ts-mode = {
    pname = "typst-ts-mode";
    version = "1367003e2ad55a2f6f9e43178584683028ab56e9";
    src = fetchgit {
      url = "https://git.sr.ht/~meow_king/typst-ts-mode";
      rev = "1367003e2ad55a2f6f9e43178584683028ab56e9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0RAJ/Td3G7FDvzf7t8csNs/uc07WUPGvMo8ako5iyl0=";
    };
    date = "2024-12-07";
  };
  verb = {
    pname = "verb";
    version = "f45e31b2bcdea2a859bb28cbb1819469978457c9";
    src = fetchFromGitHub {
      owner = "federicotdn";
      repo = "verb";
      rev = "f45e31b2bcdea2a859bb28cbb1819469978457c9";
      fetchSubmodules = false;
      sha256 = "sha256-NpEDFq0BHNaixiVFWHmgs9TixzIjh0hpYwBqP+oM+cc=";
    };
    date = "2025-12-22";
  };
  zenn-cli = {
    pname = "zenn-cli";
    version = "011ca9dc9fcf36d1339fa3487c750ce0e328b09c";
    src = fetchFromGitHub {
      owner = "wurly200a";
      repo = "zenn-cli.el";
      rev = "011ca9dc9fcf36d1339fa3487c750ce0e328b09c";
      fetchSubmodules = false;
      sha256 = "sha256-fiU9vbNzJZ5OxswqMDJPtU7xZQXUnfDVe8UMhALAn/8=";
    };
    date = "2024-11-09";
  };
}
