[[plugins]]
repo = 'neovim/nvim-lspconfig'
# on_event = ['BufEnter']
on_event = ['BufRead', 'CursorHold']
# on_event = ['LspAttach']

# Add `vim.*` in LSP suggestion
[[plugins]]
repo = 'folke/lazydev.nvim'
on_source = 'nvim-lspconfig'

# Language Server management
[[plugins]]
repo = 'williamboman/mason.nvim'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'mason.nvim'
lua_source = """
require("configs/lsp")
"""
